### ISSUE TITLE
CPT Polos >> Modal

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/rede-polos-theme#11]
Matheus, precisa aplicar um modal para abrir os Polos na home.

![layout-modal](https://cloud.githubusercontent.com/assets/3632627/8967630/7292e1b6-360e-11e5-95ed-b8eb323e0b5d.jpg)

Os dados que vai puxar serão normais: Imagem destacada, Titulo e Content.

O botão deve ser uma opção dentro do CPT, para colocar as URLs dos sites de cada polos que teremos.

**Comment by diegorojas** [comment]
@matheusgimenez em produção temos alguma coisa estranha, o plugin esta ativado, os posts setados com "Verdadeiro", a URL sendo criada, mas nada de modal.. depois veja:
http://polos.mundialfutebolderua.org/

Fica aparecendo na url um /blog que não deveria estar ali :(

**Comment by matheusgimenez** [comment]
resolvido via dashboard no site em producao
