### ISSUE TITLE
Menu >> Botao de acesso para articulação

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/rede-polos-theme#14]
Fazer um botão com css para o link de ares restrita da Rede

![botao-menu-principal](https://cloud.githubusercontent.com/assets/3632627/9186656/f90f22fc-3f9d-11e5-9478-591b437e2620.png)

**Comment by LuwkasLima** [comment]
Dica do Matheus: usa aquele esquema de setar classe css no menu, lembra?
